version: 0.2
phases:
  install:
    commands:
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/
  pre_build:
    commands:
      - aws eks update-kubeconfig --name demo-cluster --region ap-southeast-1
  build:
    commands:
      - IMAGE_URI=$(jq -r '.[0].imageUri' imagedefinitions.json)
      - echo "Deploying image: $IMAGE_URI"
      - kubectl set image deployment/my-app my-app=$IMAGE_URI -n default
      - kubectl rollout status deployment/my-app -n default